import { cleanIconTilesScript } from './cleanIconTiles'

export const baseHead = (title: string, extra = '') => `
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"/>
  <title>${title} | SalonLink</title>
  <meta name="description" content="SalonLink — Ghana's beauty booking app. Find, book and manage salon appointments."/>
  <link rel="manifest" href="/manifest.json?v=2"/>
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon.png?v=2"/>
  <meta name="theme-color" content="#ffffff"/>
  <link rel="preconnect" href="https://fonts.googleapis.com"/>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"/>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.0/css/all.min.css"/>
  <script src="https://cdn.jsdelivr.net/npm/axios@1.6.0/dist/axios.min.js"></script>
  <style>
    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
    :root{--c-void:#fff;--c-deep:#fafafa;--c-dark:#f5f5f5;--c-mid:#ebebeb;--c-surface:#fff;--c-raise:#fafafa;--g-main:#101010;--g-deep:#000;--g-light:#555;--g-dim:rgba(0,0,0,.04);--g-border:rgba(0,0,0,.08);--i-faint:rgba(0,0,0,.06);--i-ghost:rgba(0,0,0,.03);--t-primary:#101010;--t-secondary:#555;--t-muted:#888;--s-green:#00a862;--s-red:#e53935;--s-amber:#ff9500;--accent-purple:#e8d4f8;--accent-pink:#fce4ec;--hero-gradient:linear-gradient(135deg, #f5f0ff 0%, #fce4ec 50%, #fff5f5 100%);--r-md:12px;--r-lg:16px;--r-xl:24px;--ease-smooth:cubic-bezier(.4,0,.2,1)}
    html{scroll-behavior:smooth;-webkit-text-size-adjust:100%;touch-action:manipulation}input,textarea,select{font-size:16px!important}
    body{font-family:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:var(--c-void);color:var(--t-primary);min-height:100vh;overflow-x:hidden;width:100%;max-width:100vw;-webkit-font-smoothing:antialiased;font-size:15px;line-height:1.5}
    .container{width:100%;max-width:1200px;margin:0 auto;padding:0 24px}@media(max-width:900px){body{font-size:14px;padding-bottom:100px}.container{padding:0 16px}.hide-mob{display:none!important}}@media(min-width:901px){.hide-desk{display:none!important}}
    .display-hero{font-size:clamp(32px,5vw,56px);font-weight:800;line-height:1.1;letter-spacing:-0.02em}.display-xl{font-size:clamp(24px,4vw,40px);font-weight:700;letter-spacing:-0.01em}.display-lg{font-size:clamp(20px,2.8vw,28px);font-weight:700}.display-md{font-size:clamp(16px,2vw,22px);font-weight:600}.display-sm{font-size:16px;font-weight:600}.font-display{font-family:'Inter',sans-serif}.gold,.gold-gradient{color:var(--g-main)}.eyebrow{font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--t-muted)}
    .card,.surface,.surface-raise{background:var(--c-surface);border:1px solid var(--i-faint);border-radius:var(--r-xl);overflow:hidden;transition:box-shadow .2s var(--ease-smooth),transform .2s var(--ease-smooth)}.card:hover{box-shadow:0 8px 30px rgba(0,0,0,.08)}.btn-primary{display:inline-flex;align-items:center;justify-content:center;gap:8px;background:var(--g-main);color:#fff;font-size:14px;font-weight:600;border:none;border-radius:100px;padding:14px 28px;cursor:pointer;text-decoration:none;transition:all .2s var(--ease-smooth)}.btn-primary:hover{background:#2a2a2a;transform:translateY(-1px)}.btn-ghost,.btn-outline{display:inline-flex;align-items:center;justify-content:center;gap:8px;background:transparent;color:var(--t-primary);font-size:14px;font-weight:500;border:1px solid var(--g-border);border-radius:100px;padding:12px 24px;cursor:pointer;text-decoration:none;transition:all .2s var(--ease-smooth)}.btn-ghost:hover,.btn-outline:hover{border-color:var(--g-main);background:var(--g-dim)}.btn-icon{display:inline-flex;align-items:center;justify-content:center;width:44px;height:44px;background:transparent;border:1px solid var(--g-border);border-radius:50%;color:var(--t-secondary);cursor:pointer;text-decoration:none;flex-shrink:0;transition:all .2s var(--ease-smooth)}.btn-icon:hover{border-color:var(--g-main);color:var(--g-main)}
    .input{width:100%;background:var(--c-surface);border:1px solid var(--g-border);border-radius:var(--r-md);padding:14px 16px;color:var(--t-primary);font-family:'Inter',sans-serif;font-size:15px;outline:none;transition:border-color .2s}.input:focus{border-color:var(--g-main)}.input-search{background:var(--c-surface);border:1px solid var(--g-border);border-radius:100px;padding:14px 20px 14px 48px;font-size:15px;width:100%}.badge{display:inline-flex;align-items:center;gap:4px;padding:6px 12px;border-radius:100px;font-size:12px;font-weight:600;white-space:nowrap}.badge-verified{background:rgba(0,168,98,.08);color:var(--s-green)}.badge-pending{background:rgba(255,149,0,.08);color:var(--s-amber)}.badge-new{background:var(--g-main);color:#fff}
    .nav-main{position:fixed;top:0;left:0;right:0;z-index:1000;background:rgba(255,255,255,.92);backdrop-filter:blur(20px);border-bottom:1px solid var(--i-faint);padding-top:env(safe-area-inset-top)}.sl-nav-spacer{height:72px}.nav-link{color:var(--t-secondary);text-decoration:none;font-size:14px;font-weight:500;padding:8px 16px;border-radius:100px;transition:all .15s}.nav-link:hover,.nav-link.active{color:var(--g-main);background:var(--g-dim)}.mobile-nav{position:fixed;bottom:16px;left:50%;transform:translateX(-50%);width:calc(100% - 32px);max-width:420px;background:rgba(255,255,255,.95);border:1px solid var(--i-faint);border-radius:24px;padding:8px 12px;display:flex;justify-content:space-around;gap:4px;z-index:900;box-shadow:0 4px 24px rgba(0,0,0,.12)}.mobile-nav-item{flex:1;display:flex;flex-direction:column;align-items:center;gap:4px;padding:10px 6px;border-radius:16px;color:var(--t-muted);text-decoration:none;font-size:10px;font-weight:600;transition:all .15s}.mobile-nav-item i{font-size:18px}.mobile-nav-item.active{color:var(--g-main);background:var(--g-dim)}.mobile-nav-item.primary{background:var(--g-main);color:#fff;margin-top:-24px;width:56px;height:56px;flex:0 0 56px;border-radius:50%;justify-content:center;box-shadow:0 4px 16px rgba(0,0,0,.2)}.mobile-nav-item.primary i{font-size:18px}.mobile-nav-item.primary span{display:none}@media(min-width:901px){.mobile-nav{display:none}}
    @media(max-width:900px){.nav-main{padding-top:calc(env(safe-area-inset-top) + 8px)!important}.sl-nav-spacer{height:calc(64px + env(safe-area-inset-top))!important}.nav-main .container{height:48px!important;padding:0 12px!important;gap:8px!important}.nav-main a[aria-label='SalonLink home']{font-size:16px!important;gap:8px!important;min-width:0!important;flex:1 1 auto!important;max-width:150px!important;overflow:hidden!important}.nav-main a[aria-label='SalonLink home'] span:first-child{width:32px!important;height:32px!important;border-radius:10px!important;font-size:12px!important;flex:0 0 32px!important}.nav-main a[aria-label='SalonLink home'] span:last-child{font-size:16px!important;white-space:nowrap!important}#nav-auth{gap:8px!important;flex:0 0 auto!important}#nav-auth .btn-ghost{font-size:13px!important;padding:8px 12px!important}#nav-auth .btn-primary,#nav-auth button{font-size:13px!important;padding:8px 14px!important;min-width:auto!important;white-space:nowrap!important}h1{font-size:clamp(28px,7vw,42px)!important;line-height:1.1!important}h2{font-size:clamp(22px,5vw,32px)!important;line-height:1.15!important}h3{font-size:clamp(17px,4vw,22px)!important}}
    .step-node{width:36px;height:36px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:700;background:var(--c-dark);color:var(--t-muted);transition:all .2s}.step-node.active,.step-node.done{background:var(--g-main);color:#fff}.step-line{height:2px;background:var(--i-faint)}.divider{height:1px;background:var(--i-faint);width:100%}
    .fresha-card{background:#fff;border-radius:16px;overflow:hidden;border:none;box-shadow:0 1px 3px rgba(0,0,0,.08);transition:all .25s var(--ease-smooth)}.fresha-card:hover{box-shadow:0 8px 30px rgba(0,0,0,.12);transform:translateY(-4px)}.fresha-search{display:flex;align-items:center;background:#fff;border-radius:100px;box-shadow:0 2px 12px rgba(0,0,0,.08);border:1px solid var(--i-faint);overflow:hidden;transition:box-shadow .2s}.fresha-search:hover{box-shadow:0 4px 20px rgba(0,0,0,.12)}.star-rating{color:#101010;font-weight:700}
  </style>
  ${extra}
  ${cleanIconTilesScript}
`

export const navbar = (active = '') => {
  const navItems = [
    { key: 'home', label: 'Home', href: '/' },
    { key: 'discover', label: 'Discover', href: '/discover' },
    { key: 'dashboard', label: 'Dashboard', href: '/dashboard' },
  ]
  return `<nav class="nav-main" aria-label="Primary navigation"><div class="container" style="height:72px;display:flex;align-items:center;justify-content:space-between;gap:20px;"><a href="/" aria-label="SalonLink home" style="display:flex;align-items:center;gap:2px;text-decoration:none;color:var(--t-primary);font-weight:800;font-size:22px;letter-spacing:-0.03em;"><span style="color:#101010;">salon</span><span style="color:#101010;">link</span></a><div class="hide-mob" style="display:flex;align-items:center;gap:8px;">${navItems.map(item => `<a class="nav-link ${active === item.key ? 'active' : ''}" href="${item.href}">${item.label}</a>`).join('')}</div><div id="nav-auth" style="display:flex;align-items:center;gap:12px;"><a href="/register?role=provider" class="btn-ghost hide-mob" style="font-size:14px;padding:10px 20px;border:1px solid #101010;">List your business</a><a href="/login" style="font-size:14px;font-weight:500;color:#101010;text-decoration:none;padding:10px 16px;">Log in</a><button onclick="var m=document.getElementById('mobile-menu'); if(m){m.classList.toggle('hidden')}" class="btn-icon hide-desk" style="border:none;"><i class="fas fa-bars"></i></button></div></div></nav><div class="sl-nav-spacer"></div>`
}

export const mobileNav = (active = '') => {
  const items = [
    { key: 'home', label: 'Home', href: '/', icon: 'fa-house' },
    { key: 'discover', label: 'Discover', href: '/discover', icon: 'fa-magnifying-glass' },
    { key: 'dashboard', label: 'Book', href: '/dashboard', icon: 'fa-calendar-plus', primary: true },
    { key: 'messages', label: 'Messages', href: '/messages', icon: 'fa-message' },
    { key: 'settings', label: 'Settings', href: '/settings', icon: 'fa-gear' },
  ]
  return `<nav class="mobile-nav" aria-label="Mobile navigation">${items.map(item => `<a class="mobile-nav-item ${item.primary ? 'primary' : ''} ${active === item.key ? 'active' : ''}" href="${item.href}" aria-label="${item.label}"><i class="fas ${item.icon}" aria-hidden="true"></i><span>${item.label}</span></a>`).join('')}</nav>`
}

export const globalScripts = () => `
<script id="salonlink-global-scripts">
(function(){
  function s(k){try{return localStorage.getItem(k)}catch(e){return null}}
  function h(v){return String(v||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c})}
  window.showToast=window.showToast||function(m,t){var d=document.createElement('div');d.textContent=String(m||'');d.style.cssText='position:fixed;left:50%;bottom:110px;transform:translateX(-50%);z-index:99999;max-width:92vw;padding:12px 16px;border-radius:999px;background:'+(t==='error'?'#B42318':'#111')+';color:white;font:600 13px Poppins,Arial;box-shadow:0 12px 30px rgba(0,0,0,.2)';document.body.appendChild(d);setTimeout(function(){d.remove()},3200)};
  window.logout=window.logout||function(){try{['sl_token','sl_user','token','user'].forEach(function(k){localStorage.removeItem(k)})}catch(e){} location.href='/login'};
  function token(){return s('sl_token')||s('token')||''} window.getSalonLinkToken=window.getSalonLinkToken||token;
  function user(){var r=s('sl_user')||s('user');if(!r)return null;try{return JSON.parse(r)}catch(e){return null}}
  function nav(){var n=document.getElementById('nav-auth'),u=user();if(!n||!u||!token())return;var r=u.role||'customer',d=r==='admin'?'/admin':(r==='provider'?'/provider/dashboard':'/dashboard'),name=u.first_name||u.firstName||u.business_name||u.email||'Account';n.innerHTML='<a href="'+d+'" class="btn-ghost" style="font-size:9.5px;padding:6px 7px;text-decoration:none;max-width:62px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">'+h(name)+'</a><button onclick="logout()" class="btn-primary" style="font-size:9.5px;padding:7px 8px;min-width:58px;white-space:nowrap;">Sign out</button>'}
  function launchCopy(){var map={'Pay Now':'Pay at salon','Pay with Paystack':'Payment Unavailable','Confirm & Pay':'Confirm Cash Booking','Send MoMo Prompt':'Payment Unavailable','Payments secured by Paystack':'Manual/offline payment at salon','Powered by Paystack':'Payment handled at salon','Secure your slot instantly with MoMo or Card':'Payment is handled manually/offline at the salon','Secure card payment':'Online payment temporarily unavailable'};var w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);var a=[];while(w.nextNode())a.push(w.currentNode);a.forEach(function(n){var v=n.nodeValue||'';Object.keys(map).forEach(function(k){v=v.split(k).join(map[k])});n.nodeValue=v});['payment-methods','momo-input'].forEach(function(id){var e=document.getElementById(id);if(e)e.style.display='none'});var b=document.getElementById('pm-momo-btn');if(b){b.disabled=true;b.textContent='Payment Unavailable'}}
  if(window.axios&&window.axios.interceptors){window.axios.interceptors.request.use(function(c){var t=token();if(t){c.headers=c.headers||{};if(!c.headers.Authorization)c.headers.Authorization='Bearer '+t}return c})}
  function init(){nav();launchCopy();setTimeout(launchCopy,350)} if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
</script>`
